### ISSUE TITLE
Catchplay+ error

### ISSUE THREAD

**Issue by CCKNBC** [wayneclub/Subtitle-Downloader#32]
```bash
D:\GitHub\Subtitle-Downloader>python subtitle_downloader.py https://www.catchplay.com/tw/video/332c41b2-dce5-4930-82a0-1f28ec7313e5 -s 1 -e 3 -p http://127.0.0.1:7890

Proxy Status: Activated Local Proxy (http://127.0.0.1:7890)
ip: ***(TW)
Traceback (most recent call last):
  File "D:\GitHub\Subtitle-Downloader\subtitle_downloader.py", line 161, in <module>
    catchplay.main()
  File "D:\GitHub\Subtitle-Downloader\services\catchplay.py", line 244, in main
    if data['apolloState'][f'Program:{program_id}']['type'] == 'MOVIE':
KeyError: 'apolloState'
```

```json
{
    "videoId": "ae01be24-0731-11ed-83d9-02de47760d8e",
    "videoType": "vod",
    "videoUrl": "***",
    "maxBitrate": 368640000,
    "maxResolution": 1080,
    "duration": 2786,
    "defaultLanguage": {
        "audio": "zh-TW",
        "subtitle": "zh-TW"
    },
    "offline": {
        "support": false,
        "version": 3
    },
    "license": {
        "url": "https://vcmsapi.catchplay.com/video/v3/drm/license/widevine",
        "extraHeaders": {
            "Authorization": "Bearer ***",
            "ASIAPLAY-PLATFORM": "desktop",
            "ASIAPLAY-DEVICE-TYPE": "web",
            "ASIAPLAY-DEVICE-MODEL": "windows",
            "ASIAPLAY-OS-TYPE": "chrome",
            "ASIAPLAY-OS-VERSION": "103.0.0",
            "ASIAPLAY-APP-VERSION": "3.0",
            "Content-Type": "text/plain;charset=UTF-8"
        }
    },
    "cards": {
        "warning": {
            "second": 4,
            "url": "https://cms.asset.catchplay.com/ratingcard/Copyright.jpg"
        }
    }
}
```

**Comment by wayneclub** [comment]
Fixed catchplay.com issue
