### ISSUE TITLE
愛奇藝海賊王字幕無法下載

### ISSUE THREAD

**Issue by danny740211** [wayneclub/Subtitle-Downloader#60]
https://www.iq.com/album/%E8%88%AA%E6%B5%B7%E7%8E%8B-one-piece-1999-19rrh8ngb1?lang=zh_tw

顯示以下錯誤
E:\ffmpeg-20191217-bd83191-win64-shared\bin\檔案蜈蚣 下載器\Subtitle-Downloader-main\Subtitle-Downloader-main>python subtitle_downloader.py https://www.iq.com/album/%E8%88%AA%E6%B5%B7%E7%8E%8B-one-piece-1999-19rrh8ngb1?lang=zh_tw -slang all -sf .srt

航海王 One piece
Traceback (most recent call last):
  File "C:\Users\admin1\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin1\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin1\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin1\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\ffmpeg-20191217-bd83191-win64-shared\bin\檔案蜈蚣 下載器\Subtitle-Downloader-main\Subtitle-Downloader-main\subtitle_downloader.py", line 151, in <module>
    main()
  File "E:\ffmpeg-20191217-bd83191-win64-shared\bin\檔案蜈蚣 下載器\Subtitle-Downloader-main\Subtitle-Downloader-main\subtitle_downloader.py", line 140, in main
    service['class'](args).main()
  File "E:\ffmpeg-20191217-bd83191-win64-shared\bin\檔案蜈蚣 下載器\Subtitle-Downloader-main\Subtitle-Downloader-main\services\iqiyi\iqiyi.py", line 368, in main
    self.series_subtitle(
  File "E:\ffmpeg-20191217-bd83191-win64-shared\bin\檔案蜈蚣 下載器\Subtitle-Downloader-main\Subtitle-Downloader-main\services\iqiyi\iqiyi.py", line 143, in series_subtitle
    episode_list_data = res.json()
                        ^^^^^^^^^^
  File "C:\Users\admin1\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by wayneclub** [comment]
> https://www.iq.com/album/%E8%88%AA%E6%B5%B7%E7%8E%8B-one-piece-1999-19rrh8ngb1?lang=zh_tw
> 
> 顯示以下錯誤 E:\ffmpeg-20191217-bd83191-win64-shared\bin\檔案蜈蚣 下載器\Subtitle-Downloader-main\Subtitle-Downloader-main>python subtitle_downloader.py https://www.iq.com/album/%E8%88%AA%E6%B5%B7%E7%8E%8B-one-piece-1999-19rrh8ngb1?lang=zh_tw -slang all -sf .srt
> 
> 航海王 One piece Traceback (most recent call last): File "C:\Users\admin1\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\models.py", line 971, in json return complexjson.loads(self.text, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\admin1\AppData\Local\Programs\Python\Python311\Lib\json__init__.py", line 346, in loads return _default_decoder.decode(s) ^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\admin1\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 337, in decode obj, end = self.raw_decode(s, idx=_w(s, 0).end()) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\admin1\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 355, in raw_decode raise JSONDecodeError("Expecting value", s, err.value) from None json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "E:\ffmpeg-20191217-bd83191-win64-shared\bin\檔案蜈蚣 下載器\Subtitle-Downloader-main\Subtitle-Downloader-main\subtitle_downloader.py", line 151, in main() File "E:\ffmpeg-20191217-bd83191-win64-shared\bin\檔案蜈蚣 下載器\Subtitle-Downloader-main\Subtitle-Downloader-main\subtitle_downloader.py", line 140, in main service['class'](args).main() File "E:\ffmpeg-20191217-bd83191-win64-shared\bin\檔案蜈蚣 下載器\Subtitle-Downloader-main\Subtitle-Downloader-main\services\iqiyi\iqiyi.py", line 368, in main self.series_subtitle( File "E:\ffmpeg-20191217-bd83191-win64-shared\bin\檔案蜈蚣 下載器\Subtitle-Downloader-main\Subtitle-Downloader-main\services\iqiyi\iqiyi.py", line 143, in series_subtitle episode_list_data = res.json() ^^^^^^^^^^ File "C:\Users\admin1\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\models.py", line 975, in json raise RequestsJSONDecodeError(e.msg, e.doc, e.pos) requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

愛奇藝更新API，已修正
