### ISSUE TITLE
my video無法下載 KeyError: 'name'

### ISSUE THREAD

**Issue by RomaYun323** [wayneclub/Subtitle-Downloader#63]
url: https://www.myvideo.net.tw/details/0/365489
Obtaining a proxy to "tw"
 + Proxy was skipped as current region matches
Traceback (most recent call last):
  File "E:\字幕工具\Subtitle-Downloader-main\subtitle_downloader.py", line 151, in <module>
    main()
  File "E:\字幕工具\Subtitle-Downloader-main\subtitle_downloader.py", line 140, in main
    service['class'](args).main()
  File "E:\字幕工具\Subtitle-Downloader-main\services\myvideo.py", line 238, in main
    self.series_metadata(data, season_list)
  File "E:\字幕工具\Subtitle-Downloader-main\services\myvideo.py", line 65, in series_metadata
    title = data['name'].strip()
            ~~~~^^^^^^^^
KeyError: 'name'
請按任意鍵繼續 . . .

不太確定是哪裡出問題，之前可以下載

**Comment by wayneclub** [comment]
> https://www.myvideo.net.tw/details/0/365489

Fixed
