### ISSUE TITLE
Viki error

### ISSUE THREAD

**Issue by Rule1311** [wayneclub/Subtitle-Downloader#79]
I am getting the following error when  trying to download from viki:

Traceback (most recent call last):
  File "C:\Users\RJ\OneDrive\Desktop\Scripts\Subtitle-Downloader-main_1\subtitle_downloader.py", line 151, in <module>
    main()
  File "C:\Users\RJ\OneDrive\Desktop\Scripts\Subtitle-Downloader-main_1\subtitle_downloader.py", line 140, in main
    service['class'](args).main()
  File "C:\Users\RJ\OneDrive\Desktop\Scripts\Subtitle-Downloader-main_1\services\viki.py", line 237, in main
    self.token = data['userInfo']['token']
KeyError: 'token'

**Comment by wayneclub** [comment]
> I am getting the following error when trying to download from viki:
> 
> Traceback (most recent call last): File "C:\Users\RJ\OneDrive\Desktop\Scripts\Subtitle-Downloader-main_1\subtitle_downloader.py", line 151, in main() File "C:\Users\RJ\OneDrive\Desktop\Scripts\Subtitle-Downloader-main_1\subtitle_downloader.py", line 140, in main service['class'](args).main() File "C:\Users\RJ\OneDrive\Desktop\Scripts\Subtitle-Downloader-main_1\services\viki.py", line 237, in main self.token = data['userInfo']['token'] KeyError: 'token'

Viki updated the API. Subtitle-Downloader has been updated, please try again.
