### ISSUE TITLE
Failed to download subtitles from Disney Plus

### ISSUE THREAD

**Issue by rDamascena** [wayneclub/Subtitle-Downloader#88]
What is the solution to the problem below?

```
python subtitle_downloader.py https://www.disneyplus.com/browse/entity-75c90eca-8969-4edb-ac1a-7165cff2671c

Successfully logged in. Welcome **********
Traceback (most recent call last):
  File "C:\Users\Adriana\Documents\Subtitle-Downloader-main\subtitle_downloader.py", line 151, in <module>
    main()
  File "C:\Users\Adriana\Documents\Subtitle-Downloader-main\subtitle_downloader.py", line 140, in main
    service['class'](args).main()
  File "C:\Users\Adriana\Documents\Subtitle-Downloader-main\services\disneyplus\disneyplus.py", line 361, in main
    self.movie_subtitle()
  File "C:\Users\Adriana\Documents\Subtitle-Downloader-main\services\disneyplus\disneyplus.py", line 45, in movie_subtitle
    title = data['text']['title']['full']['program']['default']['content'].strip(
TypeError: 'NoneType' object is not subscriptable
```

**Comment by frankwu8765** [comment]
我也遇到完全一样的问题！不知道是不是因为disney登录之后，还需要选择相应的用户？而一般用户都设置了自己的PIN码，所以程序没有真正的登录进去！这样的话，是不是用cookie的方式更好一些？

**Comment by wayneclub** [comment]
> What is the solution to the problem below?
> 
> ```
> python subtitle_downloader.py https://www.disneyplus.com/browse/entity-75c90eca-8969-4edb-ac1a-7165cff2671c
> 
> Successfully logged in. Welcome **********
> Traceback (most recent call last):
>   File "C:\Users\Adriana\Documents\Subtitle-Downloader-main\subtitle_downloader.py", line 151, in <module>
>     main()
>   File "C:\Users\Adriana\Documents\Subtitle-Downloader-main\subtitle_downloader.py", line 140, in main
>     service['class'](args).main()
>   File "C:\Users\Adriana\Documents\Subtitle-Downloader-main\services\disneyplus\disneyplus.py", line 361, in main
>     self.movie_subtitle()
>   File "C:\Users\Adriana\Documents\Subtitle-Downloader-main\services\disneyplus\disneyplus.py", line 45, in movie_subtitle
>     title = data['text']['title']['full']['program']['default']['content'].strip(
> TypeError: 'NoneType' object is not subscriptable
> ```

Disney Update new API. Fixed. Please try again

**Comment by rDamascena** [comment]
> > What is the solution to the problem below?
> > ```
> > python subtitle_downloader.py https://www.disneyplus.com/browse/entity-75c90eca-8969-4edb-ac1a-7165cff2671c
> > 
> > Successfully logged in. Welcome **********
> > Traceback (most recent call last):
> >   File "C:\Users\Adriana\Documents\Subtitle-Downloader-main\subtitle_downloader.py", line 151, in <module>
> >     main()
> >   File "C:\Users\Adriana\Documents\Subtitle-Downloader-main\subtitle_downloader.py", line 140, in main
> >     service['class'](args).main()
> >   File "C:\Users\Adriana\Documents\Subtitle-Downloader-main\services\disneyplus\disneyplus.py", line 361, in main
> >     self.movie_subtitle()
> >   File "C:\Users\Adriana\Documents\Subtitle-Downloader-main\services\disneyplus\disneyplus.py", line 45, in movie_subtitle
> >     title = data['text']['title']['full']['program']['default']['content'].strip(
> > TypeError: 'NoneType' object is not subscriptable
> > ```
> 
> Disney Update new API. Fixed. Please try again

I tried and the error persists!

```
python subtitle_downloader.py "https://www.disneyplus.com/browse/entity-d90a933e-3b20-45a3-9bcf-b07e631a603f" --season 1

Successfully logged in. Welcome *******
Traceback (most recent call last):
  File "C:\Users\Adriana\Documents\Subtitle-Downloader-main\subtitle_downloader.py", line 151, in <module>
    main()
  File "C:\Users\Adriana\Documents\Subtitle-Downloader-main\subtitle_downloader.py", line 140, in main
    service['class'](args).main()
  File "C:\Users\Adriana\Documents\Subtitle-Downloader-main\services\disneyplus\disneyplus.py", line 370, in main
    self.movie_subtitle()
  File "C:\Users\Adriana\Documents\Subtitle-Downloader-main\services\disneyplus\disneyplus.py", line 46, in movie_subtitle
    title = data['text']['title']['full']['program']['default']['content'].strip(
TypeError: 'NoneType' object is not subscriptable
```

**Comment by wayneclub** [comment]
> https://www.disneyplus.com/browse/entity-75c90eca-8969-4edb-ac1a-7165cff2671c

I mean I had updated the project need to redownload and try again.

**Comment by achatschnecke** [comment]
> > https://www.disneyplus.com/browse/entity-75c90eca-8969-4edb-ac1a-7165cff2671c
> 
> I mean I had updated the project need to redownload and try again.

It is working for movies only. If I try to download a series the json-response seems to be empty.

**Comment by Manujito** [comment]
> Edit: The recognition for difference between movies and TV shows needs to be updated. I solved it for me by forcing to use the "series_subtitle"-method at the end of the ./Subtitle-Downloader/services/disneyplus/disneyplus.py

Thanks to your tip I was able to download tv shows again.

But now I have a different issue. After a couple of days of usage, now Disney started requiring a one-time code sent via email every time I login. This has made the script stop working with the error "Error: [{'code': 'throttled'}]"

Any way to fix this?
