### ISSUE TITLE
下載愛奇藝航海王字幕異常無法完全下載完畢

### ISSUE THREAD

**Issue by danny740211** [wayneclub/Subtitle-Downloader#94]
https://www.iq.com/album/%E8%88%AA%E6%B5%B7%E7%8E%8B-one-piece-1999-19rrh8ngb1?lang=zh_tw

下載到一半就異常無法下載完成
Finding 航海王.One.piece.S01E1042.WEB-DL.iQIYI.vtt ...
Finding 航海王.One.piece.S01E1043.WEB-DL.iQIYI.vtt ...
Finding 航海王.One.piece.S01E1044.WEB-DL.iQIYI.vtt ...
Finding 航海王.One.piece.S01E1009.WEB-DL.iQIYI.vtt ...
Finding 航海王.One.piece.S01E1010.WEB-DL.iQIYI.vtt ...
Finding 航海王.One.piece.S01E1011.WEB-DL.iQIYI.vtt ...
Finding 航海王.One.piece.S01E1012.WEB-DL.iQIYI.vtt ...
Finding 航海王.One.piece.S01E1013.WEB-DL.iQIYI.vtt ...
Traceback (most recent call last):
  File "C:\Users\admin1\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 537, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin1\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connection.py", line 461, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin1\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 1375, in getresponse
    response.begin()
  File "C:\Users\admin1\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 318, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin1\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin1\AppData\Local\Programs\Python\Python311\Lib\socket.py", line 706, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin1\AppData\Local\Programs\Python\Python311\Lib\ssl.py", line 1278, in recv_into
    return self.read(nbytes, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin1\AppData\Local\Programs\Python\Python311\Lib\ssl.py", line 1134, in read
    return self._sslobj.read(len, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TimeoutError: The read operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\admin1\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "C:\Users\admin1\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 845, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin1\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\util\retry.py", line 470, in increment
    raise reraise(type(error), error, _stacktrace)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin1\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\util\util.py", line 39, in reraise
    raise value
  File "C:\Users\admin1\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 791, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin1\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 539, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "C:\Users\admin1\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 371, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='www.iq.com', port=443): Read timed out. (read timeout=5)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "G:\bilibili\Subtitle-Downloader-main\Subtitle-Downloader-main\subtitle_downloader.py", line 151, in <module>
    main()
  File "G:\bilibili\Subtitle-Downloader-main\Subtitle-Downloader-main\subtitle_downloader.py", line 140, in main
    service['class'](args).main()
  File "G:\bilibili\Subtitle-Downloader-main\Subtitle-Downloader-main\services\iqiyi\iqiyi.py", line 361, in main
    self.series_subtitle(
  File "G:\bilibili\Subtitle-Downloader-main\Subtitle-Downloader-main\services\iqiyi\iqiyi.py", line 181, in series_subtitle
    vid = self.get_vid(play_url)
          ^^^^^^^^^^^^^^^^^^^^^^
  File "G:\bilibili\Subtitle-Downloader-main\Subtitle-Downloader-main\services\iqiyi\iqiyi.py", line 39, in get_vid
    res = self.session.get(play_url, timeout=5)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin1\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin1\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin1\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin1\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\adapters.py", line 532, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='www.iq.com', port=443): Read timed out. (read timeout=5)
請按任意鍵繼續 . . .

**Comment by wayneclub** [comment]
iq.com有修正，請重新下載
